export const robotChatFormList = [
  {
    name: 'customerName',
    label: '客户姓名',
    type: 'input',
    placeholder: '请输入客户姓名',
    rules: [{ required: true, message: '请输入客户姓名' }],
  },

  {
    name: 'telephone',
    label: '电话号码',
    type: 'input',
    placeholder: '',
    rules: [{ required: true, message: '请输入电话号码' }],
  },
  {
    name: 'sex',
    label: '性别',
    type: 'radio',
    placeholder: '',
    rules: [{ required: true, message: '请选择性别' }],
  },
  // {
  //   name: 'callLine',
  //   label: '呼叫线路',
  //   type: 'select',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请选择呼叫线路' }],
  // },
  // {
  //   name: 'voice',
  //   label: '音色',
  //   type: 'select',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请选择音色' }],
  // },
  // {
  //   name: 'judicialState',
  //   label: '司法状态',
  //   type: 'select',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请选择司法状态' }],
  // },
  // {
  //   name: 'judicialChannel',
  //   label: '司法渠道',
  //   type: 'select',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请选择司法渠道' }],
  // },
  // {
  //   name: 'overdueDays',
  //   label: '逾期天数',
  //   type: 'input',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请输入逾期天数' }],
  // },
  // {
  //   name: 'overdueNumber',
  //   label: '逾期笔数',
  //   type: 'input',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请输入逾期笔数' }],
  // },
  // {
  //   name: 'genderName',
  //   label: '性别称呼',
  //   type: 'radio',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请输入性别称呼' }],
  // },
  // {
  //   name: 'customerType',
  //   label: '客户类型',
  //   type: 'select',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请选择客户类型' }],
  // },
  // {
  //   name: 'settledAmount',
  //   label: '结清金额',
  //   type: 'input',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请输入结清金额' }],
  // },
  // {
  //   name: 'overdueMoney',
  //   label: '逾期金额',
  //   type: 'input',
  //   placeholder: '',
  //   rules: [{ required: true, message: '请输入逾期金额' }],
  // },
];
